package havis.net.ui.shared.client.chart;

public enum LabelPosition {
	LEFT_OUTER_TOP,
	LEFT_OUTER_MIDDLE,
	LEFT_OUTER_BOTTOM,
	LEFT_INNER_TOP,
	LEFT_INNER_MIDDLE,
	LEFT_INNER_BOTTOM,
	RIGHT_OUTER_TOP,
	RIGHT_OUTER_MIDDLE,
	RIGHT_OUTER_BOTTOM,
	RIGHT_INNER_TOP,
	RIGHT_INNER_MIDDLE,
	RIGHT_INNER_BOTTOM;
}
